# Site settings
title: Phoenix Perry
subtitle: Cultural Engineer, Game Designer, Insigator, Feminist Killjoy.
email: contact@phoenixperry.com
description: Game Designer, Code Liberation Founder, educator
baseurl: "/peg" # the subpath of your site, e.g. /blog
url: "https://phoenixperry.github.io/" the base hostname & protocol for your site
# author:
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# Social settings
500px_url:
# facebook_url:
github_url: http://github.com/phoenixperry
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/phoenixperry
# pinterest_url:
medium_url: https://medium.com/@phoenixperry
slack_url:
twitter_url: https://twitter.com/phoenixperry

# # Sass building
# sass:
#     sass_dir: _sass

# Build settings
markdown: kramdown
