# Site settings
title: Playful Experiences Group
subtitle: by PEG
email: contact@phoenixperry.com
description: Experimental Game Design and writing
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Phoenix Perry
street_address: Goldsmiths Unviersity
city: London
state: London
zip_code: SE13
country: UK
phone:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
